export PYTHONUNBUFFERED=1
export VLLM_USE_V1=1
export HYDRA_FULL_ERROR=0
export WANDB_PROJECT="PPO_critic"
export SLURM_JOB_ID="ds_1d5b_chunk_boundary_critic_256"

# When true, math_dapo incorrect answers get reward 0.0 instead of -1.0.
MATH_DAPO_BINARY_REWARD=true

python3 -m verl.trainer.main_ppo \
  data.train_files=/data/shuozhe/saved_dataset/MetaMathQA-math-500/train.parquet \
  data.val_files=/data/shuozhe/saved_dataset/MetaMathQA-math-500/test.parquet \
  data.prompt_key=prompt \
  +data.response_key=ground_truth \
  data.train_batch_size=32 \
  data.max_prompt_length=2048 \
  data.max_response_length=2048 \
  actor_rollout_ref.model.path=/data/shuozhe/verl/train_log/job_05b_vh_init_e5_metamath/global_step_800/merged_hf/actor \
  actor_rollout_ref.actor.optim.lr=1e-6 \
  actor_rollout_ref.actor.ppo_mini_batch_size=32 \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
  actor_rollout_ref.actor.fsdp_config.param_offload=False \
  actor_rollout_ref.actor.use_kl_loss=False \
  actor_rollout_ref.ref.fsdp_config.param_offload=True \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
  actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
  actor_rollout_ref.rollout.enforce_eager=True \
  actor_rollout_ref.rollout.free_cache_engine=True \
  actor_rollout_ref.rollout.enable_chunked_prefill=True \
  actor_rollout_ref.rollout.do_sample=True \
  actor_rollout_ref.rollout.temperature=1.0 \
  actor_rollout_ref.rollout.top_p=1.0 \
  actor_rollout_ref.rollout.top_k=-1 \
  actor_rollout_ref.rollout.n=1 \
  actor_rollout_ref.rollout.checkpoint_engine.update_weights_bucket_megabytes=4096 \
  actor_rollout_ref.hybrid_engine=True \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
  critic.optim.lr=1e-5 \
  critic.model.path=/data/shuozhe/saved_model/DeepSeek-R1-Distill-Qwen-1.5B \
  critic.model.external_lib=trl \
  critic.model.value_head_init_mean=0.0 \
  critic.model.value_head_init_std=0.00001 \
  critic.model.fsdp_config.param_offload=False \
  critic.value_head_type=scalar \
  critic.ppo_micro_batch_size_per_gpu=4 \
  algorithm.use_kl_in_reward=False \
  algorithm.chunk_boundary_critic.enable=True \
  algorithm.chunk_boundary_critic.chunk_size=256 \
  algorithm.chunk_boundary_critic.loss_type=bce \
  algorithm.chunk_boundary_critic.uniform_per_state_weight=False \
  +reward.reward_kwargs.math_dapo_binary_reward=${MATH_DAPO_BINARY_REWARD} \
  trainer.val_before_train=True \
  trainer.n_gpus_per_node=4 \
  trainer.nnodes=1 \
  trainer.use_legacy_worker_impl=enable \
  trainer.test_freq=50 \
  trainer.save_freq=50 \
  trainer.total_epochs=5 \
  trainer.logger='["console","wandb"]' \
  trainer.project_name="PPO_critic" \
  trainer.experiment_name="qwen2.5_0.5B_chunk_boundary_critic_${SLURM_JOB_ID}" \
  trainer.default_local_dir="/data/shuozhe/verl/train_log/job_${SLURM_JOB_ID}" \
  2>&1 | tee /data/shuozhe/verl/train_log/job_${SLURM_JOB_ID}.txt
